name: Update Main README

on:
  push:
    paths:
      - 'Active/**'
      - 'Completed/**'
      - '.github/workflows/update-readme.yml'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install R dependencies (if needed)
        run: Rscript -e 'install.packages("fs", repos="https://cloud.r-project.org")'

      - name: Run README update script
        run: Rscript .github/scripts/update_main_readme.R

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m "Auto-update README with project links" || echo "No changes to commit"
          git push
